name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.DEPLOY }}" > "$HOME/.ssh/DEPLOY"
      - run: chmod 600 "$HOME/.ssh/DEPLOY"
      # Build
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean install package -DskipTests --file pom.xml
      # Deploy
      - run: rsync -e "ssh -p 22 -i $HOME/.ssh/DEPLOY -o StrictHostKeyChecking=no" --archive --compress --delete . root@91.238.99.217:/home/
